name: Weather App Workflow

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache Python dependencies
      uses: actions/cache@v3  # v3로 변경
      with:
        path: ~/.cache/pip  # 캐시할 경로
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}  # 캐시 키 (requirements.txt 변경 시 새 캐시)
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the weather app
      run: |
        python main.py
